require:
  - rubocop-rails
  - rubocop-rspec

inherit_from:
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
