Menu.create!(title: "牛乳", price: 200)
Menu.create!(title: "たまご", price: 500)
Menu.create!(title: "ラーメン", price: 700)
Menu.create!(title: "にんじん", price: 300)
Menu.create!(title: "トマト", price: 100)
Menu.create!(title: "あんこう", price: 1200)
